baseURL = "http://novao.xyz/"
languageCode = "en-us"
title = "Novao Technologies"
copyright = "Novao Technologies"
theme = "novao"
[Params]
### BASE CONFIGURATION (Required) ###

    # Path to the static directory where the kit from https://realfavicongenerator.net/ was put.
    icons = "/icons/"

    # Short Title. Used for "app name" when pinning to homescreen.
    shortTitle = "Novao"

    # Accent Color. Used for various things around the site. Hexadecimal format.
    accent = "#123587"